language: python

before_install:
  - wget https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz
  - tar xzf Python-3.10.0.tgz
  - cd Python-3.10.0
  - ./configure --enable-optimizations
  - make altinstall
  - cd ..

install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
script:
  - flake8 .
#  - python manage.py test
